# Generated by Django 4.1.4 on 2023-01-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("from_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("retrieving_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TempMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("temp_email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ("email_username", models.CharField(max_length=255)),
                (
                    "email_domain",
                    models.CharField(
                        choices=[
                            ("1secmail.com", "1secmail.com"),
                            ("1secmail.org", "1secmail.org"),
                            ("1secmail.net", "1secmail.net"),
                            ("bheps.com", "bheps.com"),
                            ("dcctb.com", "dcctb.com"),
                            ("kzccv.com", "kzccv.com"),
                            ("qiott.com", "qiott.com"),
                            ("wuuvo.com", "wuuvo.com"),
                        ],
                        default="1secmail.com",
                        max_length=255,
                    ),
                ),
                ("messages", models.ManyToManyField(blank=True, related_name="temp_email", to="temp_mail.message")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_email",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary mail",
                "verbose_name_plural": "Temporary mails",
                "ordering": ("-created_at",),
            },
        ),
    ]
