# Generated by Django 4.1.4 on 2023-01-03 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('temp_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('email_username', models.CharField(max_length=255)),
                ('email_domain', models.CharField(default='1secmail.com', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary mail',
                'verbose_name_plural': 'Temporary mails',
                'ordering': ('-created_at',),
            },
        ),
    ]
