# Generated by Django 4.1.4 on 2022-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('temp_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('retrieving_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TempMail',
                'verbose_name_plural': 'TempMails',
                'ordering': ('-retrieving_date',),
            },
        ),
    ]
