# Generated by Django 4.1.4 on 2023-01-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0002_message_tempmail_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
