# Generated by Django 4.1.4 on 2022-12-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0003_tempmail_email_domain_tempmail_email_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('message_id', models.CharField(max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('retrieving_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-retrieving_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='tempmail',
            options={'ordering': ('-created_at',), 'verbose_name': 'TempMail', 'verbose_name_plural': 'TempMails'},
        ),
        migrations.RemoveField(
            model_name='tempmail',
            name='body',
        ),
        migrations.RemoveField(
            model_name='tempmail',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='tempmail',
            name='retrieving_date',
        ),
        migrations.RemoveField(
            model_name='tempmail',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tempmail',
            name='user',
        ),
        migrations.AddField(
            model_name='tempmail',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_email', to='temp_mail.message'),
        ),
    ]
