# Generated by Django 4.1.4 on 2023-01-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0003_remove_message_id_alter_message_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmail',
            name='email_domain',
            field=models.CharField(choices=[('1secmail.com', '1secmail.com'), ('1secmail.org', '1secmail.org'), ('1secmail.net', '1secmail.net'), ('wwjmp.com', 'wwjmp.com'), ('esiix.com', 'esiix.com'), ('xojxe.com', 'xojxe.com'), ('yoggm.com', 'yoggm.com')], default='1secmail.com', max_length=255),
        ),
    ]
