# Generated by Django 4.1.4 on 2022-12-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0004_message_alter_tempmail_options_remove_tempmail_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmail',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
