# Generated by Django 4.1.4 on 2022-12-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0005_alter_tempmail_temp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmail',
            name='email_domain',
            field=models.CharField(choices=[('1secmail.com', '1secmail.com'), ('1secmail.org', '1secmail.org'), ('1secmail.net', '1secmail.net'), ('wwjmp.com', 'wwjmp.com'), ('esiix.com', 'esiix.com'), ('xojxe.com', 'xojxe.com'), ('yoggm.com', 'yoggm.com')], default='1secmail.com', max_length=255),
        ),
    ]
