# Generated by Django 4.1.4 on 2022-12-26 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temp_mail', '0006_alter_tempmail_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
