# Generated by Django 4.1.4 on 2022-12-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0007_tempmail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='temporary_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='temp_mail.tempmail'),
        ),
    ]
