# Generated by Django 4.1.4 on 2022-12-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0008_message_temporary_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmail',
            name='message',
        ),
    ]
