# Generated by Django 4.1.4 on 2022-12-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0009_remove_tempmail_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='temporary_mail',
            new_name='temp_email',
        ),
    ]
