# Generated by Django 4.1.4 on 2022-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0011_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmail',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
