# Generated by Django 4.1.4 on 2022-12-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0013_alter_tempmail_email_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='temp_email',
        ),
    ]
