# Generated by Django 4.1.4 on 2022-12-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0014_remove_message_temp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
