# Generated by Django 4.1.4 on 2022-12-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0015_alter_message_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
