# Generated by Django 4.1.4 on 2022-12-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0016_remove_message_id_alter_message_message_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempmail',
            options={'ordering': ('-created_at',), 'verbose_name': 'Temporary Mail', 'verbose_name_plural': 'Temporary Mails'},
        ),
    ]
