# Generated by Django 4.1.4 on 2022-12-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_mail', '0017_alter_tempmail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempmail',
            options={'ordering': ('-created_at',), 'verbose_name': 'Temporary mail', 'verbose_name_plural': 'Temporary mails'},
        ),
    ]
