# Generated by Django 4.1.4 on 2022-12-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('methods', '0002_alter_email_created_at_alter_email_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imei',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to=settings.AUTH_USER_MODEL),
        ),
    ]
