name: black Lint

on: [ pull_request ]

jobs:
  black-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: black Lint
        uses: psf/black@stable
        with:
          args: --check --diff --exclude migrations