name: pre-commit

on:
  pull_request:
  push:
    branches:
      - master
      - development

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v4.4.0
      with:
        extra_args:
                - flake8 --all-files
                - black --check --diff --line-length 120
